# Generated by Django 4.1.3 on 2022-11-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depopower', '0004_alter_canava_firstrow_secondcolumn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canava',
            name='firstRow_secondColumn',
            field=models.ForeignKey(default='Свободно', on_delete=django.db.models.deletion.CASCADE, related_name='firstRow_secondColumn', to='depopower.locomotive'),
        ),
        migrations.AlterField(
            model_name='canava',
            name='secondRow_firstColumn',
            field=models.ForeignKey(default='Профильное', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='secondRow_firstColumn', to='depopower.locomotive'),
        ),
    ]
