# Generated by Django 4.1.3 on 2022-11-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depopower', '0005_alter_canava_firstrow_secondcolumn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canava',
            name='firstRow_firstColumn',
        ),
        migrations.RemoveField(
            model_name='canava',
            name='firstRow_secondColumn',
        ),
        migrations.RemoveField(
            model_name='canava',
            name='firstRow_thirdColumn',
        ),
        migrations.RemoveField(
            model_name='canava',
            name='secondRow_firstColumn',
        ),
        migrations.RemoveField(
            model_name='canava',
            name='secondRow_secondColumn',
        ),
        migrations.RemoveField(
            model_name='canava',
            name='secondRow_thirdColumn',
        ),
        migrations.RemoveField(
            model_name='canava',
            name='thirdRow_firstColumn',
        ),
        migrations.RemoveField(
            model_name='canava',
            name='thirdRow_secondColumn',
        ),
        migrations.RemoveField(
            model_name='canava',
            name='thirdRow_thirdColumn',
        ),
        migrations.AddField(
            model_name='canava',
            name='machine',
            field=models.ForeignKey(default='Свободно', on_delete=django.db.models.deletion.CASCADE, to='depopower.locomotive'),
        ),
        migrations.AddField(
            model_name='canava',
            name='place_column',
            field=models.IntegerField(default=1, verbose_name='Column'),
        ),
        migrations.AddField(
            model_name='canava',
            name='place_row',
            field=models.IntegerField(default=1, verbose_name='Row'),
        ),
    ]
