# Generated by Django 4.1.3 on 2022-11-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depopower', '0006_remove_canava_firstrow_firstcolumn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canava',
            name='depo_name',
        ),
        migrations.AddField(
            model_name='canava',
            name='record_name',
            field=models.TextField(default='rls-depo', max_length=144, primary_key=True, serialize=False, verbose_name='Name of record'),
        ),
    ]
