# Generated by Django 4.1.3 on 2022-11-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depopower', '0007_remove_canava_depo_name_canava_record_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Volume')),
                ('locomotive', models.ForeignKey(default='Свободно', on_delete=django.db.models.deletion.CASCADE, to='depopower.locomotive')),
                ('month', models.ForeignKey(default='Dec[2023]', on_delete=django.db.models.deletion.CASCADE, to='depopower.monthworkday')),
                ('techwork', models.ForeignKey(default='TO-3', on_delete=django.db.models.deletion.CASCADE, to='depopower.availabletechwork')),
            ],
            options={
                'verbose_name': 'CellRecord',
                'verbose_name_plural': 'CellRecords',
                'unique_together': {('locomotive', 'techwork', 'month')},
            },
        ),
    ]
