# Generated by Django 4.1.3 on 2022-11-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depopower', '0009_alter_cellrecord_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techwork',
            name='hours',
        ),
        migrations.AddField(
            model_name='techwork',
            name='loaded_days',
            field=models.FloatField(default=0, verbose_name='Count of loaded days'),
        ),
        migrations.AlterField(
            model_name='techwork',
            name='days',
            field=models.FloatField(default=0, verbose_name='Count of days'),
        ),
    ]
