# Generated by Django 4.1.3 on 2022-11-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depopower', '0010_remove_techwork_hours_techwork_loaded_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techwork',
            name='days',
        ),
        migrations.RemoveField(
            model_name='techwork',
            name='loaded_days',
        ),
        migrations.AddField(
            model_name='techwork',
            name='norms_in_days',
            field=models.FloatField(default=0, verbose_name='Norms in days'),
        ),
    ]
