# Generated by Django 4.1.3 on 2022-11-29 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depopower', '0011_remove_techwork_days_remove_techwork_loaded_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellrecord',
            name='locomotive',
            field=models.ForeignKey(default='ТЭМ2', on_delete=django.db.models.deletion.CASCADE, to='depopower.locomotive'),
        ),
    ]
